### ISSUE TITLE
Recolor xp bar number doesnt either for me and my friend

### ISSUE THREAD

**Issue by Sdemonthys** [McTsts/shader-utilities#19]
Hey! So I tried to implement your shader that allows us to change xp bar number color in 1.21 but it doesnt seem to load at all, it displays this errors in the logs:

Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.

And

Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
    at auk.a(SourceFile:69)
    at bph.d(SourceFile:162)
    at bpl.d(SourceFile:23)
    at bph.B(SourceFile:136)
    at bph.bB(SourceFile:121)
    at fgo.c(SourceFile:1240)
    at fgo.f(SourceFile:882)
    at net.minecraft.client.main.Main.main(SourceFile:256)
Caused by: java.lang.RuntimeException: could not reload shaders
    at ges.c(SourceFile:537)
    at ges$1.a(SourceFile:419)
    at ges$1.a(SourceFile:396)
    at auj.a(SourceFile:13)
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
    ... 9 more
Caused by: aku: Invalid shaders/core/rendertype_text.json: Couldn't compile vertex program (file/Test, rendertype_text) : 0(29) : error C1102: incompatible type for parameter #1 ("pos.12")
0(29) : error C7623: implicit narrowing of type from "vec3" to "int"
0(29) : error C1104: too many parameters in function call
    at aku.a(SourceFile:48)
    at gfn.<init>(SourceFile:172)
    at ges.c(SourceFile:516)
    ... 13 more
Caused by: java.io.IOException: Couldn't compile vertex program (file/Test, rendertype_text) : 0(29) : error C1102: incompatible type for parameter #1 ("pos.12")
0(29) : error C7623: implicit narrowing of type from "vec3" to "int"
0(29) : error C1104: too many parameters in function call
    at faw.b(SourceFile:69)
    at faw.a(SourceFile:51)
    at gfn.a(SourceFile:210)
    at gfn.<init>(SourceFile:157)
    ... 14 more
    
    
    Is there a way to fix this on my side?

**Comment by McTsts** [comment]
This shader hasn't been updated since 1.18 so it will likely need some updating. Possibly some of the parts that come from vanilla have changed and need updating. To do this you could check the vanilla 1.18 shader, see which lines in the shader here are added/modified, and then apply these modifications onto the 1.21 version of the shader.

I plan to update these shaders to a newer version at some point, but it probably won't be very soon.
